import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './components/**/*.{vue,ts}',
    './pages/**/*.vue',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      colors: {
        macaron: {
          bg: 'var(--macaron-bg)',
          card: 'var(--macaron-card)',
          border: 'var(--macaron-border)',
          text: 'var(--macaron-text)',
          'text-secondary': 'var(--macaron-text-secondary)',
          cta: 'var(--macaron-cta)',
          'cta-hover': 'var(--macaron-cta-hover)',
          muted: 'var(--macaron-muted)',
          'muted-light': 'var(--macaron-muted-light)',
          'progress-track': 'var(--macaron-progress-track)',
          'surface-alt': 'var(--macaron-surface-alt)',
          'surface-hover-alt': 'var(--macaron-surface-hover-alt)',
          'graph-bg': 'var(--macaron-graph-bg)',
          'svg-guide': 'var(--macaron-svg-guide)',
          'input-bg': 'var(--macaron-input-bg)',
          'hover-bg': 'var(--macaron-hover-bg)',
        },
        category: {
          economics: '#A07850',
          psychology: '#7A906B',
          law: '#6080A0',
          medicine: '#B0905B',
          astronomy: '#8060A0',
          geography: '#509880',
          politics: '#B07850',
          biology: '#509050',
          philosophy: '#9050A0',
          literature: '#A87050',
          art: '#B05070',
          music: '#509888',
          mathematics: '#5070A0',
          ecology: '#409050',
          animals: '#A08B50',
          plants: '#609040',
          food: '#B09040',
          sports: '#B05050',
          military: '#909050',
          education: '#5070A8',
          communication: '#B05060',
          'scientific-method': '#5088A0',
          'data-thinking': '#9050A8',
        },
      },
      fontFamily: {
        heading: ['"Noto Serif SC"', '"Crimson Pro"', 'serif'],
        body: ['Inter', '"Noto Sans SC"', '"Source Han Sans"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'card': '16px',
      },
      boxShadow: {
        'card': '0 2px 12px rgba(0, 0, 0, 0.06)',
        'card-hover': '0 4px 20px rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
} satisfies Config
