import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './components/**/*.{vue,ts}',
    './pages/**/*.vue',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      colors: {
        macaron: {
          bg: 'var(--macaron-bg)',
          card: 'var(--macaron-card)',
          border: 'var(--macaron-border)',
          text: 'var(--macaron-text)',
          'text-secondary': 'var(--macaron-text-secondary)',
          cta: 'var(--macaron-cta)',
          'cta-hover': 'var(--macaron-cta-hover)',
          muted: 'var(--macaron-muted)',
          'muted-light': 'var(--macaron-muted-light)',
          'progress-track': 'var(--macaron-progress-track)',
          'surface-alt': 'var(--macaron-surface-alt)',
          'surface-hover-alt': 'var(--macaron-surface-hover-alt)',
          'graph-bg': 'var(--macaron-graph-bg)',
          'svg-guide': 'var(--macaron-svg-guide)',
          'input-bg': 'var(--macaron-input-bg)',
          'hover-bg': 'var(--macaron-hover-bg)',
        },
        category: {
          economics: '#A07850',
          psychology: '#7A906B',
          law: '#6080A0',
          medicine: '#B0905B',
          astronomy: '#8060A0',
          geography: '#509880',
          politics: '#B07850',
          biology: '#509050',
          philosophy: '#9050A0',
          literature: '#A87050',
          art: '#B05070',
          music: '#509888',
          mathematics: '#5070A0',
          ecology: '#409050',
          animals: '#A08B50',
          plants: '#609040',
          food: '#B09040',
          sports: '#B05050',
          military: '#909050',
          education: '#5070A8',
          communication: '#B05060',
          'scientific-method': '#5088A0',
          'data-thinking': '#9050A8',
          architecture: '#8B7B6B',
          'design-thinking': '#A06080',
          'daily-life': '#A08B70',
          'healthy-living': '#50A890',
          'emotional-intelligence': '#C07878',
          'cognitive-biases': '#9B7070',
          'game-theory': '#5A7A7A',
          'mythology': '#907868',
          'criminology': '#687888',
          'paradoxes': '#8868A0',
          'human-limits': '#A86848',
          'unsolved-mysteries': '#7068A8',
          'humor': '#B8A060',
          'logical-fallacies': '#889878',
          'lost-civilizations': '#A09080',
          'materials-science': '#587880',
        },
      },
      fontFamily: {
        heading: ['"Noto Serif SC"', '"Crimson Pro"', 'serif'],
        body: ['Inter', '"Noto Sans SC"', '"Source Han Sans"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'card': '16px',
      },
      boxShadow: {
        'card': '0 2px 12px rgba(0, 0, 0, 0.06)',
        'card-hover': '0 8px 30px rgba(0, 0, 0, 0.1)',
        'glow': '0 0 20px rgba(111, 78, 55, 0.15)',
      },
      spacing: {
        'gutter': '1.5rem',
        'section': '4rem',
        'section-lg': '6rem',
      },
      transitionDuration: {
        'fast': '150ms',
        'base': '250ms',
        'slow': '400ms',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      fontSize: {
        'display': ['clamp(2rem, 5vw, 3.5rem)', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'title': ['clamp(1.5rem, 3vw, 2rem)', { lineHeight: '1.2' }],
        'subtitle': ['clamp(1rem, 2vw, 1.25rem)', { lineHeight: '1.4' }],
      },
      animation: {
        'fade-in-up': 'fade-in-up 400ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in-scale': 'fade-in-scale 300ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'shimmer': 'shimmer 1.5s infinite',
      },
      keyframes: {
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-scale': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config
